### ISSUE TITLE
Colorize directory with ls++.conf

### ISSUE THREAD

**Issue by Hywan** [trapd00r/ls--#25]
Hi,

How can I specify a color only for directories with ls++.conf?
Thanks!

**Comment by trapd00r** [comment]
[Now you can.](https://github.com/trapd00r/ls--/blob/master/ls%2B%2B.conf#L34)

**Comment by trapd00r** [comment]
Well, between then and now, life happened.

**Comment by Hywan** [comment]
I totally understand that!
