### ISSUE TITLE
No color and incorrect formatting on gentoo

### ISSUE THREAD

**Issue by joe9** [trapd00r/ls--#30]
Hello,

This is the output on a new machine (gentoo distro) with ls++

ls++
 drwxrxrx7  hour            4K bin
 drwxrxrx4  day             4K boot
 drwxrxrx2  day           3.7K dev
 drwxrxrx25 sec             4K etc
 drwxrxrx<  day             4K home
 drwxrxrx3  day             4K lib32
 drwxrxrx26 hour            4K lib64
 drwxrxrx4  day             4K media
 drwxrxrx<  day             4K mnt
 drwxrxrx4  day             4K opt
 drxrxrx2  day             0B proc
 drwx8  hour            4K root
 drwxrxrx4  day             4K run
 drwxrxrx<  day             4K sbin
 drxrxrx2  day             0B sys
 drwxrwxrwt29 sec           720B tmp
 drwxrxrx4  day             4K usr
 drwxrxrx3  day             4K var
 lrwxrwxrwx3  day             5B lib  lib64
 rwrr4  day             162M stage3-amd64-20130130.tar.bz2

perl --version

This is perl 5, version 16, subversion 2 (v5.16.2) built for x86_64-linux
(with 22 registered patches, see perl -V for more detail)

Copyright 1987-2012, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

This is the output on a different box on which ls++ works like a charm.

ls++
│drwxr xr x│8  day │   4K│bin
│drwxr xr x│8  day │   1K│boot
│drwxr xr x│2  day │ 3.7K│dev
│drwxr xr x│27 min │   4K│etc
│drwxr xr x│7  mon │   4K│etc.original
│drwxr xr x│23 day │   4K│home
│drwxr xr x│4  mon │   4K│include.to_delete
│drwxr xr x│7  day │   4K│lib
│drwx      │7  mon │  16K│lost+found
│drwxr xr x│5  day │   4K│mnt
│drwxr xr x│<  mon │   4K│opt
│dr xr xr x│2  day │   -B│proc
│drwxr x   │13 day │   4K│root
│drwxr xr x│<  day │ 120B│run
│drwxr xr x│7  day │   4K│sbin
│dr xr xr x│2  day │   -B│sys
│drwxrwxrwt│37 sec │ 700B│tmp
│drwxr xr x│24 hour│   4K│usr
│drwxr xr x│5  day │   4K│var
│ rw r  r  │7  mon │ 247M│crux-2.7.1-x86_64-updated.iso
│lrwxrwxrwx│<  mon │   3B│lib64 =>lib

Any suggestions on what I could be missing, please?

Thanks
Joe

**Comment by trapd00r** [comment]
Most probably a $TERM issue and most likely resolved by now.
