### ISSUE TITLE
Output changed when piped

### ISSUE THREAD

**Issue by AlexandreRio** [trapd00r/ls--#32]
I've noticed that the output change when the command is piped ( I don't know if it's the expected behavior ).

`ls++ dir1/ dir2/` just list the content
`ls++ dir1/ dir2/ | grep .` list the content and display the directories name, like with /bin/ls

**Comment by Alsan** [comment]
It's because of the ANSI color code, try redirect the output to a file will see what's happen.

This might help:
```bash
ls++ | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g" | more
```

**Comment by trapd00r** [comment]
It is intended. isa_tty() checks if we're connected to a terminal or not.
