### ISSUE TITLE
Using --potsf on Mac prints perms/group/last modified/size, but no filename

### ISSUE THREAD

**Issue by plttn** [trapd00r/ls--#48]
Using --potsf on Mac gives me this output. Not sure what the issue is.
<img width="499" alt="screen shot 2015-08-25 at 5 59 30 pm" src="https://cloud.githubusercontent.com/assets/7369280/9483289/14c7a59e-4b53-11e5-90eb-8e85b0e435ca.png">

**Comment by the0demiurge** [comment]
same issue
