### ISSUE TITLE
missing git relese tags for v0.345

### ISSUE THREAD

**Issue by anthraxx** [trapd00r/ls--#49]
Hi,
I'm a package maintainer and it would be cool if you can keep the git tags in sync

**Comment by anthraxx** [comment]
@trapd00r  PS: maybe you want to look at my pull requests #50 and #51 and issue a new release tag after this :yum:

**Comment by anthraxx** [comment]
can we get a new tag for e17221c78f398fc9180631c684cdefabb45d1595 pointing to 0.36

**Comment by trapd00r** [comment]
I'll be better at this @anthraxx
