### ISSUE TITLE
Can't locate Term/ExtendedColor in @INC (macOS)

### ISSUE THREAD

**Issue by Jarvvski** [trapd00r/ls--#52]
I've used the cpan::ExtendedColor as included in the readme

I've also tried manually installing via the tar on CPANs site.

The files seem to be in '$HOME/.cpan/builds' but @INC is looking in:

```
/usr/local/Cellar/perl/5.24.0_1/lib/perl5/site_perl/5.24.0/darwin-thread-multi-2level /usr/local/Cellar/perl/5.24.0_1/lib/perl5/site_perl/5.24.0 /usr/local/Cellar/perl/5.24.0_1/lib/perl5/5.24.0/darwin-thread-multi-2level /usr/local/Cellar/perl/5.24.0_1/lib/perl5/5.24.0 /usr/local/lib/perl5/site_perl/5.24.0
```

macOS Sierra 10.12.2

Any ideas @trapd00r ?

**Comment by matthutchinson** [comment]
+1 me too - same deal ❓

**Comment by bauen1** [comment]
```
cpan Term::ExtendedColor
```
did the trick for me (found in the installation instructions)
