### ISSUE TITLE
Makefile fails when /usr/local/etc/ directory present.

### ISSUE THREAD

**Issue by MrMino** [trapd00r/ls--#53]
Here be logs.
Ubuntu Gnome 16.04:

    cp ls++ blib/script/ls++
    "/usr/bin/perl" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/ls++
    Manifying 2 pod documents
    "/usr/bin/perl" -pi -e "s|\"/etc/ls\+\+\.conf|\"/usr/local/etc/ls++.conf|g" ls++
    Appending installation info to /usr/local/lib/x86_64-linux-gnu/perl/5.22.1/perllocal.pod
    [ ! -d /usr/local/etc ] && mkdir -p /usr/local/etc
    Makefile:889: recipe for target 'install_vendor' failed
    make: *** [install_vendor] Error 1

**Comment by jaredmcateer** [comment]
Anyone looking for a workaround if the folder was empty like it was for me, just remove it. Otherwise you can mv the folder and then copy the files back into the new dir or cp ls++.conf into the old one and then mv it back.

**Comment by MrMino** [comment]
Looks dead / not worth keeping on my issue list, hence closing.
