### ISSUE TITLE
Setup own colour

### ISSUE THREAD

**Issue by RupankarGhosh** [trapd00r/ls--#58]
I love the colours but there is only 4 colour scheme in config file.Can I all more colour schemes in it or ho can I change the pre-difined colours.

Also can I add colours in the folder's name section too?The folder's name section shows colours as normal ls do.

**Comment by trapd00r** [comment]
Yes, you can add any arbitary colorscheme in the config. Just copy an
existing colorscheme and change it to your liking, i.e:

```
 elsif($colorscheme eq 'rupankar') {
  $c[0]  = 1;
  $c[1]  = 2;
  $c[2]  = 4;
  $c[3]  = 8;
  $c[4]  = 16;
  $c[5]  = 32;
  $c[6]  = 64;
  $c[7]  = 128;
  ...
}  
```
