### ISSUE TITLE
Screenshots in readme are broken

### ISSUE THREAD

**Issue by kapsh** [trapd00r/ls--#59]
Cannot see screenshots in readme:

![image](https://user-images.githubusercontent.com/144717/38150338-1a2cb72c-3467-11e8-99e8-955279b626fe.png)

Direct link https://camo.githubusercontent.com/c269167445a710f7e316b4f54d3b7f9123353b04/687474703a2f2f692e6a6170682e73652f6c732d2d5f67685f73637265656e73686f742e706e67 gives "Error Fetching Resource".

Maybe it is a temporary difficulties though.

**Comment by trapd00r** [comment]
Fixed.
