### ISSUE TITLE
Ubuntu 18.04 packet not existing

### ISSUE THREAD

**Issue by Segaja** [trapd00r/ls--#66]
According to the readme `ls++` should exist as package in Ubuntu/Debian. This doesn't seem to be the case for ubuntu 18.04 (server version).

Is this just a case of the package is missing or is the readme wrong?

**Comment by fcanela** [comment]
@trapd00r This issue gave me a good scare!

As the package does not exist when performing `apt-get install ls++` the + symbol is interpreted as a wildcard. Then apt proceeds to try to install the 2741 packages that match this. Fortunately, it failed because of broken packages dependencies.

**Comment by trapd00r** [comment]
@fcanela, interesting indeed, haha!

I'll update the readme, not sure what has happened.
